---
# Common Tasks

- name: Ensure zookeeper host exists
  fail: msg="One, or no zookeeper host may be specified."
  when: "groups.get('zookeeper_servers', [])|length < 1"

- name: Ensure kafka host exists
  fail: msg="One, or no kafka host may be specified."
  when: "groups.get('kafka_servers', [])|length < 1"
